---
- name: Pi Setup
  hosts: all
  vars:
    upgrade_file: /root/pi_setup_upgrade_complete
  tasks:
    - include: setup_boot_config.yml
    - include: setup_ssh.yml
    - include: setup_packages.yml
    - include: setup_user.yml user_name=pi
    - include: setup_user.yml user_name=root
    - include: setup_octoprint.yml
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
      become: true

    # static: false can be removed once 2.1.2 is released
    - name: reboot
      include: handler_reboot.yml
      static: false
