---
- name: Pi Setup
  hosts: all
  vars:
    upgrade_file: /root/pi_setup_upgrade_complete
  tasks:
    - include: gather_facts.yml
    - include: setup_boot_config.yml
    - include: setup_ssh.yml
    - include: setup_packages.yml
    - include: setup_user.yml user_name=pi
    - include: setup_user.yml user_name=root
    - include: setup_octoprint.yml
    - include: setup_camera_server.yml
  handlers:
    # static: false can be removed once 2.1.2 is released
    - name: restart sshd
      include: handler_restart_sshd.yml
      static: false

    # static: false can be removed once 2.1.2 is released
    - name: reboot
      include: handler_reboot.yml
      static: false
