---
- name: Pi Setup
  hosts: all
  vars:
    upgrade_file: /root/pi_setup_upgrade_complete
  tasks:
    - include: setup_boot_config.yml
    - include: setup_ssh.yml
    - include: setup_packages.yml
    - include: setup_user.yml user_name=pi
    - include: setup_user.yml user_name=root
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
      become: true
