---
- name: Pi Setup
  hosts: all
  vars:
    var_path: /var/ansible
    upgrade_file: upgrade_complete
    resize_file: resize_complete
  tasks:
    - include: gather_facts.yml

    - include: setup_boot_config.yml
      become: true

    - include: setup_ssh.yml

    - include: setup_packages.yml
      become: true

    - include: setup_user.yml user_name=pi

    - include: setup_user.yml user_name=root

    - include: setup_camera_server.yml
      when: setup_camera_server

    - include: setup_docker.yml
      become: true
      when: setup_docker

    - include: setup_phatdac.yml
      become: true
      when: setup_phatdac

    - include: setup_i2c.yml
      become: true
      when: setup_i2c

  handlers:
    # static: false required again as of 2.2.1
    - name: restart sshd
      include: handler_restart_sshd.yml
      static: false

    # static: false required again as of 2.2.1
    - name: reboot
      include: handler_reboot.yml
      static: false

    - name: enable swap mem
      service: name=dphys-swapfile enabled=yes state=restarted
      become: true
