---
- name: Set HDMI group
  lineinfile: dest=/boot/config.txt regexp='^hdmi_group=' line='hdmi_group={{ setup_hdmi_group }}' state=present
  become: true
  notify: reboot

- name: Set HDMI mode
  lineinfile: dest=/boot/config.txt regexp='^hdmi_mode=' line='hdmi_mode={{ setup_hdmi_mode }}' state=present
  become: true
  notify: reboot

- name: LCD rotate (for Pimoroni LCD case)
  lineinfile: dest=/boot/config.txt regexp='^lcd_rotate=' line='lcd_rotate=2' state=present
  become: true
  notify: reboot

- name: Set GPU
  lineinfile: dest=/boot/config.txt regexp='^gpu_mem=' line='gpu_mem={{ setup_gpu_mem }}' state=present
  become: true
  notify: reboot

- name: Enable camera
  lineinfile: dest=/boot/config.txt regexp='^start_x=' line='start_x=1' state=present
  become: true
  when: setup_camera
  notify: reboot

- name: Enable wlan0
  lineinfile: dest=/etc/network/interfaces regexp='^iface wlan0 ' line='iface wlan0 inet dhcp' state=present
  become: true
  when: setup_wifi

- name: Write network config
  template: src=wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600
  become: true
  when: setup_wifi
  notify: reboot

- name: Enable 1 wire
  lineinfile: dest=/boot/config.txt line='dtoverlay=w1-gpio' state=present
  become: true
  when: setup_w1_gpio
  notify: reboot
