---
- name: Set HDMI group
  lineinfile: dest=/boot/config.txt regexp='^hdmi_group=' line='hdmi_group={{ setup_hdmi_group }}' state=present
  notify: reboot

- name: Set HDMI mode
  lineinfile: dest=/boot/config.txt regexp='^hdmi_mode=' line='hdmi_mode={{ setup_hdmi_mode }}' state=present
  notify: reboot

- name: LCD rotate (for Pimoroni LCD case)
  lineinfile: dest=/boot/config.txt regexp='^lcd_rotate=' line='lcd_rotate=2' state=present
  notify: reboot

- name: Set GPU
  lineinfile: dest=/boot/config.txt regexp='^gpu_mem=' line='gpu_mem={{ setup_gpu_mem }}' state=present
  notify: reboot

- name: Install swap memory package
  apt: pkg=dphys-swapfile state=present
  when: setup_swap_mem | int > 0

- name: Set swap memory
  lineinfile: dest=/etc/dphys-swapfile regexp='^CONF_SWAPSIZE=' line='CONF_SWAPSIZE={{ setup_swap_mem }}' state=present
  when: setup_swap_mem | int > 0
  notify: enable swap mem

- name: Enable camera
  lineinfile: dest=/boot/config.txt regexp='^start_x=' line='start_x=1' state=present
  when: setup_camera
  notify: reboot

- name: Enable wlan0
  lineinfile: dest=/etc/network/interfaces regexp='^iface wlan0 ' line='iface wlan0 inet dhcp' state=present
  when: setup_wifi

- name: Write network config
  template: src=wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600
  when: setup_wifi
  notify: reboot

- name: Enable 1 wire
  lineinfile: dest=/boot/config.txt line='dtoverlay=w1-gpio' state=present
  when: setup_w1_gpio
  notify: reboot
